name: Snyk Open Source Test

on:
  workflow_dispatch:
  workflow_call:

  schedule:
           # ┌───────────── minute (0 - 59)
           # │ ┌───────────── hour (0 - 23)
           # │ │ ┌───────────── day of the month (1 - 31)
           # │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
           # │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
           # │ │ │ │ │
           # │ │ │ │ │
           # │ │ │ │ │
           # * * * * *
    - cron: '30 2 * * 1-5'

  push:
    branches:
      - 'main'

jobs:
  open-source-test:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Repo
          uses: actions/checkout@master

        - name: Setup JDK 17
          uses: actions/setup-java@v4
          with:
            java-version: '17'
            distribution: 'temurin'
            architecture: x64
            cache: 'maven'

        - name: Maven verify
          run: mvn --batch-mode --update-snapshots verify

        - name: Install Maven dependencies
          run: mvn clean install

        - uses: snyk/actions/setup@master
        - name: Test Open Source Dependencies with Snyk
          run: snyk test --all-projects
          env:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}